### PR TITLE
Ping/pong example for README

### PR DESCRIPTION
**Pull request by trusktr**
I thought that the ping/pong example better shows the power of CSP, plus it's familiar with people coming from other languages. I also used a custom `sleep` function to show the power of async/await in general, for people who are just starting to discover these concepts.

### CODE REVIEW

**Comment by trusktr** [comment]
@dvlsg There we go, synced the README example with the one in the examples folder. I couple things to note:

* I removed the `let log = ...` assignment and used console.log directly.
* Removed the Ball class, it was too simple and extra reading.
* Removed eslint comment.
* Remove parameter types.

The reason for those four changes is to keep it as minimal as possible for the learning reader. Any thoughts on that?

**Comment by dvlsg** [comment]
Those changes are all great, good call.

Two final questions -- what's the tilde in `~async` [here](https://github.com/trusktr/async-csp/commit/aa5e480dc369b300f0372efbb8f330ae9d74a4fc#diff-04c6e90faac2675aa89e2176d2eec7d8R27)? I don't recognize that syntax.

And how do you feel about naming the running function and executing it on the following line for readability? Might just be me, but I think I would personally miss the IIFE at first glance. Maybe. (I'm not super picky either way, just a thought).

But yeah, looks great! Thanks! You can squash/rebase if you want, otherwise I'll just merge it in directly.

**Comment by trusktr** [comment]
@dvlsg 

> what's the tilde in ~async here?

It makes the `async function() {}` a function expression, which can be immediately invoked. basically,

```js
~function() {
  // ...
}()
```

is functionally the same as

```js
(function() {
  // ...
})()
```

The tilde operator operates on the value of the expression, which results in nothing since the result isn't saved. If we try

```js
function() {
  // ...
}()
```

we'll get a SyntaxError.

Basically, using the tilde expression is my favorite way of writing an IIFE. There's other ways too:

```js
(function(){ /* code */ }())
!function(){ /* code */ }()
-function(){ /* code */ }()
+function(){ /* code */ }()
```

I originally found that in [this nice article](http://benalman.com/news/2010/11/immediately-invoked-function-expression/).

> how do you feel about naming the running function and executing it on the following line for readability

I'm okay with that. Maybe the IIFE is more noticeable after having seen that article? x] But yeah, my original intent was to make the example as low level as possible for the learning developer, so perhaps running the function instead of using an IIFE might suit that goal.

**Comment by trusktr** [comment]
There we go, updated with no IIFE.

**Comment by trusktr** [comment]
Aaaaaaaand squashed!

**Comment by trusktr** [comment]
For fun, I found some other ways to make an IIFE:

```js
typeof function() {}()
delete function() {}()
void function() {}()
new function() {}()
0*function() {}()
0,function() {}()
0>>>function() {}()
iife>function() {}()
iife|function() {}()
```

That last one is interesting.

```js
iife|async function() {
  // ..
  await something()
  // ...
}()
```

**Comment by dvlsg** [comment]
Haha oh javascript. That's clever. I actually use few async IIFEs internally, but I opted for the `(async () => { /*... */ })();` syntax.

I'm curious to see if the `do` expressions are going to be moved up past [stage 0](https://github.com/tc39/ecma262/blob/master/stage0.md) any time soon. I know they technically work in babel already.

Either way, looks good! Thanks for the contribution, I appreciate it.

**Comment by trusktr** [comment]
@dvlsg Ah, so `do { ... }` is basically like an IIFE (I'm guessing with it's own scope)? That's interesting!

**Comment by trusktr** [comment]
@dvlsg I thought I'd add to the previous discusson on IIFEs. I re-stumbled on this, which shows why the tilde prefix on the IIFE is better than other options: http://www.joezimjs.com/javascript/great-mystery-of-the-tilde/#comment-654736283

**Pull request merged**
