### PR TITLE
Added polyfill to webpack build

### PR DESCRIPTION
**Pull request by XVincentX**
I just realised that you're externalising regenerators. Those must be included in the browser build. This PR will fix this.

### CODE REVIEW

**Comment by dvlsg** [comment]
I don't believe this is necessary. Webpack should automatically inline any external dependencies (which is both a blessing and a curse).

I refactored the build stages into specific cjs / umd pipes, and included minified /  uncompressed files where relevant. Can you grab the latest source from git, build, then take a look at `./examples/browser/index.html`? You should be able to just load that `index.html` from your filesystem and see the `async-csp` output running in your console, provided your environment is relatively new (chrome, has access to Promises, etc). If you are unable to run that, let me know what browser version you are using and post the errors.

**Comment by XVincentX** [comment]
That's true, but your babelrc file has a plugin which is avoiding regenerator incorporation
Have a look here: http://s.codepen.io/XVincentX/debug/VayNMr

image

**Comment by dvlsg** [comment]
Looks [included](https://github.com/dvlsg/async-csp/blob/4728a522e6a21118b0e94dad575947c3eb563bab/dist/umd/async-csp.js#L2723) to me. The error on your codepen is from the transpiled ping pong piece, not the source file itself.

async-csp-browser-console

async-csp-browser-index

**Comment by XVincentX** [comment]
Whoops, you're right.

**Pull request closed without merging**
